# Generated by Django 3.2.11 on 2022-06-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkpage",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="snippets.speaker",
                verbose_name="Speaker",
            ),
        ),
    ]
